version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout            
      - run: 
          name: install
          command: |
            ant init-ivy
            ant resolve
            ant dependencytree
            bash <(curl -s https://scripts.scantist.com/staging/ci-circle.sh)
